services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - main-network

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - main-network

  framework_base:
    build:
      context: ./framework_base

  producer:
    build:
      context: ./producer
    container_name: producer
    volumes:
      - ./shared_data:/src/shared
    depends_on:
      - framework_base
      - kafka
    ports:
      - "6000:6000"
    networks:
      - main-network

  predictor:
    build:
      context: ./predictor
    container_name: predictor
    volumes:
      - ./shared_data:/src/shared
    depends_on:
      - framework_base
      - kafka
    ports:
      - "6001:6001"
    networks:
      - main-network

  benign_time_classifier:
    build:
      context: ./classifiers/benign_time_classifier
    container_name: benign_time_classifier
    volumes:
      - ./shared_data:/src/shared
    depends_on:
      - framework_base
      - kafka
    ports:
      - "5001:5001"
    networks:
      - main-network

  benign_ip_src_classifier:
    build:
      context: ./classifiers/benign_ip_src_classifier
    container_name: benign_ip_src_classifier
    volumes:
      - ./shared_data:/src/shared
    depends_on:
      - framework_base
      - kafka
    ports:
      - "5002:5002"
    networks:
      - main-network
  
  benign_ip_dst_classifier:
    build:
      context: ./classifiers/benign_ip_dst_classifier
    container_name: benign_ip_dst_classifier
    volumes:
      - ./shared_data:/src/shared
    depends_on:
      - framework_base
      - kafka
    ports:
      - "5003:5003"
    networks:
      - main-network

networks:
  main-network:
    driver: bridge
